services:
  index:
    extends:
      file: docker-compose.yml
      service: index

  app:
    extends:
      file: docker-compose.yml
      service: app
    environment:
      YENTE_MANIFEST: "manifests/commercial.yml"
      OPENSANCTIONS_DELIVERY_TOKEN: "your-secret-token"

volumes:
  index-os-data: null
