# mypy: ignore-errors
#
# Fixtures strategy: when adding a test, pull in the smallest dataset that has
# what you need via @pytest.mark.usefixtures("<fixture_name>"):
#
#   - zala_test_dataset:          small local sanctions cluster (Zakharov + Zala Aero)
#   - parteispenden_test_dataset: small local dataset of German political donations
#
# For tests that exercise something very specific (a particular catalog shape,
# scoping behaviour, etc.), prefer building a custom minimal manifest inline
# in the test instead of adding a new shared fixture. This keeps each test
# unit-testy (one thing under test), reduces fixture sprawl, and avoids
# cross-test coupling. See test_catalog in tests/test_base.py for an example.
import re
import pytest_asyncio
from datetime import datetime
from typing import Any
from uuid import uuid4
from pathlib import Path
from unittest.mock import Mock, patch
from contextlib import asynccontextmanager, contextmanager
from fastapi.testclient import TestClient
from followthemoney import model
from followthemoney.dataset.util import dataset_name_check
import orjson

from opentelemetry import metrics
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import InMemoryMetricReader

from yente import settings
from yente.app import create_app
from yente.search.indexer import update_index
from yente.provider import with_provider, close_provider
from yente.data.manifest import Catalog, Manifest
import yente.data


# In-memory OpenTelemetry metric reader so tests can assert on gauge values.
# MeterProvider can only be set once globally, so we wire it up at module import.
metric_reader = InMemoryMetricReader()
metrics.set_meter_provider(MeterProvider(metric_readers=[metric_reader]))


@asynccontextmanager
async def patch_yente_catalog(manifest: Manifest):
    old_catalog = yente.data._catalog
    yente.data._catalog = await Catalog.load(manifest)
    try:
        yield
    finally:
        yente.data._catalog = old_catalog


run_id = uuid4().hex
settings.TESTING = True
FIXTURES_PATH = Path(__file__).parent / "fixtures"
VERSIONS_PATH = FIXTURES_PATH / "versions.json"

# If we ever hit get_catalog, which reads settings.MANIFEST, we will crash. Instead, tests that don't explicitly declare
# what test data fixture they want will end up using `empty_catalog`.
settings.MANIFEST = None
# Used as a prefix for all indices created during a single test run, used in
# cleanup_test_indices to delete them after the run.
settings.INDEX_NAME = f"yente-test-{run_id}"
# Must not be an prefix of the index names generated by build_index_alias_name_for_fixture,
# otherwise the orphan cleanup will delete the other fixture indices.
settings.ENTITY_INDEX = f"{settings.INDEX_NAME}-empty"
settings.AUTO_REINDEX = False

app = create_app()
client = TestClient(app)


@pytest_asyncio.fixture(scope="session", autouse=True)
async def cleanup_test_indices():
    yield
    async with with_provider() as provider:
        for index in await provider.get_all_indices():
            if index.startswith(settings.INDEX_NAME):
                await provider.delete_index(index)


# autouse=True makes this the "outermost" fixture, which just sets an empty catalog.
# This can get overridden temporarily by function-scoped fixtures.
@pytest_asyncio.fixture(scope="session", autouse=True)
async def empty_catalog():
    async with patch_yente_catalog(Manifest.model_validate({})):
        yield


# The basic idea is to have each fixture operate in a separate index prefix.
# This is a work-around to allow multiple fixtures to be loaded at the same time
# without stepping on each other's toes. In an ideal world, we would just make
# the fixtures function-scoped, but that would mean reindexing multiple times
# during testing, which is slow
def build_index_alias_name_for_fixture(fixture_name: str) -> str:
    return f"{settings.INDEX_NAME}-fixture-{fixture_name}"


PARTEISPENDEN_MANIFEST = Manifest.model_validate(
    {
        "datasets": [
            {
                "name": "parteispenden",
                "title": "German political party donations",
                "entities_url": (
                    FIXTURES_PATH / "dataset" / "parteispenden" / "entities.ftm.json"
                ).as_uri(),
                "load": True,
            }
        ]
    }
)


@pytest_asyncio.fixture(scope="function", autouse=False)
async def parteispenden_test_dataset(monkeypatch):
    monkeypatch.setattr(
        settings,
        "ENTITY_INDEX",
        build_index_alias_name_for_fixture("parteispenden"),
    )
    async with patch_yente_catalog(PARTEISPENDEN_MANIFEST):
        # This call will only index the first time the fixture is used,
        # all subsequent uses will be fast.
        await update_index()
        yield


ZALA_MANIFEST = Manifest.model_validate(
    {
        "datasets": [
            {
                "name": "zala",
                "title": "Zala Test Dataset",
                "entities_url": (
                    FIXTURES_PATH / "dataset" / "zala" / "entities.ftm.json"
                ).as_uri(),
                "load": True,
            }
        ]
    }
)


@pytest_asyncio.fixture(scope="function", autouse=False)
async def zala_test_dataset(monkeypatch):
    monkeypatch.setattr(
        settings,
        "ENTITY_INDEX",
        build_index_alias_name_for_fixture("zala"),
    )
    async with patch_yente_catalog(ZALA_MANIFEST):
        # This call will only index the first time the fixture is used,
        # all subsequent uses will be fast.
        await update_index()
        yield


@pytest_asyncio.fixture(scope="function", autouse=False)
async def search_provider():
    async with with_provider() as provider:
        yield provider


@pytest_asyncio.fixture(autouse=True)
async def flush_cached_es():
    """Reference: https://github.com/pytest-dev/pytest-asyncio/issues/38#issuecomment-264418154"""
    try:
        yield
    finally:
        await close_provider()


# Wire format for first_seen / last_seen / last_change on API responses.
# 19 chars, ISO 8601, `T` separator, seconds precision, no fractional
# seconds and no timezone suffix — e.g. "2023-04-20T18:00:25". Kept tight
# because changing how Pydantic models build (validate vs. construct) can
# silently shift this format and downstream consumers depend on it.
ISO_SECONDS_NO_TZ = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$")


def assert_iso_seconds_no_tz(value: str) -> None:
    assert isinstance(value, str), (type(value), value)
    assert ISO_SECONDS_NO_TZ.match(value), value
    # Belt-and-braces: it should parse as a naive datetime and round-trip.
    parsed = datetime.fromisoformat(value)
    assert parsed.tzinfo is None, value
    assert parsed.microsecond == 0, value
    assert parsed.isoformat() == value, value


# Minimum wire shape of an EntityResponse. Responses are built via
# model_construct, which skips pydantic validation — so any drift in the
# ES payload (renamed keys, type changes) would pass straight through to
# clients unnoticed. This set pins what clients are guaranteed to see;
# subclasses like ScoredEntityResponse add more keys on top.
REQUIRED_ENTITY_KEYS = {
    "id",
    "caption",
    "schema",
    "properties",
    "datasets",
    "referents",
    "target",
    "first_seen",
    "last_seen",
    "last_change",
}


def assert_entity_shape(data: dict[str, Any]) -> None:
    missing = REQUIRED_ENTITY_KEYS - data.keys()
    assert not missing, (missing, sorted(data.keys()))
    assert isinstance(data["id"], str) and data["id"], data["id"]
    assert isinstance(data["caption"], str) and data["caption"], data["caption"]
    assert data["schema"] in model.schemata, data["schema"]
    assert isinstance(data["properties"], dict), data["properties"]
    for prop, values in data["properties"].items():
        assert isinstance(prop, str), prop
        assert isinstance(values, list), (prop, values)
        for value in values:
            # Nested entity references appear as dicts in nested=true responses
            # and must themselves be well-shaped EntityResponses.
            if isinstance(value, dict):
                assert_entity_shape(value)
            else:
                assert isinstance(value, str), (prop, value)
    assert isinstance(data["datasets"], list), data["datasets"]
    for name in data["datasets"]:
        assert isinstance(name, str), name
        dataset_name_check(name)
    assert isinstance(data["referents"], list), data["referents"]
    assert all(isinstance(r, str) for r in data["referents"]), data["referents"]
    assert isinstance(data["target"], bool), data["target"]
    for key in ("first_seen", "last_seen", "last_change"):
        if data[key] is not None:
            assert_iso_seconds_no_tz(data[key])


@contextmanager
def patch_catalog_response(response_data: dict):
    """Context manager to patch AsyncClient for catalog responses."""
    mock_response = Mock()
    mock_response.content = orjson.dumps(response_data)

    with patch(
        "yente.data.util.httpx.AsyncClient", autospec=True
    ) as mock_client_constructor:
        mock_client = mock_client_constructor.return_value.__aenter__.return_value
        mock_client.get.return_value = mock_response
        yield mock_client, mock_client_constructor
